"""The Python calculator must match the Node output frozen in tests/golden/.

Fixtures were generated by tests/parity/gen_golden.py at migration time. No
runtime dependency on Node.
"""
import json
from pathlib import Path

from app.tools.mulesoft.calculator import calculate_assessment

GOLDEN = json.loads((Path(__file__).parent / "golden" / "mulesoft.json").read_text(encoding="utf-8"))


def test_python_calculator_matches_golden():
    assert GOLDEN, "golden fixtures missing"
    for case in GOLDEN:
        actual = calculate_assessment(case["input"])
        # Round-trip so int/float JSON representations compare equal.
        assert json.loads(json.dumps(actual)) == case["expected"], f"mismatch for input: {case['input']}"
